1| # Bu araç @keyiflerolsun tarafından | @KekikAkademi için yazılmıştır.
2| name: CloudStream Derleyici
3| 
4| concurrency:
5|   group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
6|   cancel-in-progress: true
7| 
8| on:
9|   workflow_dispatch:
10|   push:
11|     branches:
12|       - master
13|     paths-ignore:
14|       - "**/*.md"
15|       - "**/*.yml"
16|       - "**/*.jpg"
17|       - "**/*.png"
18|       - "**/*.py"
19| 
20| jobs:
21|   CloudStreamDerleyici:
22|     runs-on: ubuntu-latest
23|     steps:
24|       - name: "'src' Depo Kontrolü"
25|         uses: actions/checkout@v4.2.2
26|         with:
27|           path: "src"
28| 
29|       - name: "'build' Depo Kontrolü"
30|         uses: actions/checkout@v4.2.2
31|         with:
32|           ref: "builds"
33|           path: "builds"
34| 
35|       - name: Eski Derlemeleri Temizle
36|         run: rm $GITHUB_WORKSPACE/builds/*.cs3 || true
37| 
38|       - name: JDK 17 Ayarla
39|         uses: actions/setup-java@v4.6.0
40|         with:
41|           distribution: adopt
42|           java-version: 17
43| 
44|       - name: Android SDK Ayarla
45|         uses: android-actions/setup-android@v3.2.2
46| 
47|       - name: Eklentileri Derle
48|         run: |
49|           cd $GITHUB_WORKSPACE/src
50|           chmod +x gradlew
51|           ./gradlew make makePluginsJson
52|           cp **/build/*.cs3 $GITHUB_WORKSPACE/builds
53|           cp build/plugins.json $GITHUB_WORKSPACE/builds
54| 
55|        - name: Derlemeleri Yükle
56|          run: |
57|            cd $GITHUB_WORKSPACE/builds
58|            git config --local user.email "actions@github.com"
59|            git config --local user.name "GitHub Actions"
60|            git add .
61|            git commit --amend -m "$GITHUB_SHA 'nın Derlenmesi" || exit 0   # eğer commit edilecek bir şey yoksa hata verme
62|            git push --force
63| 
